select 
saddr, 
SID, 
serial# ser#, 
-- audsid, 
-- paddr, 
-- user#, 
username, 
command cmd, 
ownerid,
taddr, 
lockwait, 
s.status, 
-- server, 
-- schema#, 
schemaname sch, 
osuser, 
-- process,
machine, 
-- port, 
terminal, 
program, 
TYPE, 
sql_address, 
-- sql_hash_value,
s.sql_id, 
s.sql_child_number sql_child, 
-- prev_sql_addr, 
-- prev_hash_value, 
-- prev_sql_id,
-- prev_child_number, 
-- plsql_entry_object_id, 
-- plsql_entry_subprogram_id,
-- plsql_object_id, 
-- plsql_subprogram_id, 
s.module, 
-- module_hash, 
s.action,
s.action_hash ahash, 
client_info cli_info, 
-- fixed_table_sequence, 
row_wait_obj#,
o.object_name,
-- row_wait_file#, 
row_wait_block#, 
row_wait_row#, 
logon_time,
last_call_et, 
-- pdml_enabled, 
-- failover_type, 
-- failover_method,
-- failed_over, 
-- resource_consumer_group, 
-- pdml_status, 
-- pddl_status,
-- pq_status, 
current_queue_duration curr_q_duration, 
client_identifier cli_identifier,
blocking_session_status blk_sess_status, 
blocking_instance blk_instance, 
blocking_session blk_sess, 
seq#,
event#, 
event, 
p1text, 
p1, 
p1raw, 
p2text, 
p2, 
p2raw, 
p3text, 
p3, 
p3raw,
wait_class_id, 
wait_class#, 
wait_class, 
wait_time, 
seconds_in_wait,
state, 
service_name, 
-- sql_trace, 
-- sql_trace_waits, 
-- sql_trace_binds, 
-- ecid,
dbms_lob.SUBSTR(sqlt.sql_text,100,1)
from 
v$session s
left outer join all_objects o on s.row_wait_obj#=o.object_id 
left outer join v$sql sqlt    on s.sql_id = sqlt.sql_id 
where s.type = 'USER' and s.status = 'ACTIVE' ;
